apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
spec:
  selector:
    matchLabels:
      app: mysql # has to match .spec.template.metadata.labels
  serviceName: "mysql"
  replicas:  # by default is 1
  template:
    metadata:
      labels:
        app: mysql # has to match .spec.selector.matchLabels
    spec:
      #terminationGracePeriodSeconds: 10
      containers:
      - name: mysqlc
        image: docker.io/relax27/mysql2:latest
        ports:
        - containerPort: 3306
          name: ml

