apiVersion: v1
kind: Service
metadata:
  name: exload
spec:
  selector:
    app: ast
  ports:
    - port: 5060
      name: n1
      targetPort: 5060
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer 
